### ISSUE TITLE
Invalid rpc nodes

### ISSUE THREAD

**Issue by baktun14** [akash-network/rpc-proxy#10]
We were doing some testing with the proxy and came across connectivity issues. Some of the rpc nodes under the proxy are either returning errors or an html page.

Here's the list of faulty nodes I found:

- https://public.stakewolle.com/cosmos/akash/rpc
- https://rpc-akash-ia.cosmosia.notional.ventures/
- https://akash-rpc.publicnode.com/

![image](https://github.com/user-attachments/assets/64d3a9eb-fdfd-4ecd-89c6-ab5ce24edae8)

**Comment by caarlos0** [comment]
should we maybe remove these nodes from https://raw.githubusercontent.com/cosmos/chain-registry/master/akash/chain.json ?

I noticed that while working on this, assumed it was a temporary error or that I needed some sort of api key...

**Comment by caarlos0** [comment]
we could store status codes in a histogram or in some buckets and use that as an heuristic to determine if the node is healthy or not, along with response time. 

do you think that makes sense?

**Comment by baktun14** [comment]
Yea, I think keeping track of the status of each nodes makes the most sense to me. I don't think we want to manually filter which ones currently work or not.

**Comment by caarlos0** [comment]
forgot to mention, but #12 should do it
