### ISSUE TITLE
Add support for REST api proxy

### ISSUE THREAD

**Issue by baktun14** [akash-network/rpc-proxy#9]
Just like the rpc proxy, we would need to also have a proxy for REST apis. It would be great to have the swagger documentation of the API with the available endpoints.

A live example of this is the cosmos directory:
https://cosmos.directory/akash
https://rpc.cosmos.directory/akash
https://rest.cosmos.directory/akash

Example REST api swagger documentation (it doesn't have all the custom endpoints for Akash, but it would be amazing to have them):
https://akash-api.polkachu.com/swagger/#

**Comment by caarlos0** [comment]
should we get the seed nodes from [here](https://raw.githubusercontent.com/cosmos/chain-registry/master/akash/chain.json) too?

and to confirm, this is supposed to be a forward proxy as well, correct?

**Comment by caarlos0** [comment]
> Btw for RPC, is it possible to remove this node from the list (https://akash-rpc.publicnode.com/)? It returns an html page at the root instead of the available endpoints. I also got error 403, 404 and 502 from the rpc proxy.

i added an error-rate health thing in #12, which should take care of it 

if it is really invalid, it should prob be removed from the list in https://raw.githubusercontent.com/cosmos/chain-registry/master/akash/chain.json - not sure if that's desirable or not, though

**Comment by caarlos0** [comment]
see #13
